version: '3.5'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'db_pass'
      POSTGRES_USER: 'db_user'
      POSTGRES_DB: 'db_name'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

  back:
    image: arcanjo-back
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DIR_PREFIX=/storage/
    volumes:
      - "D:/:/storage"
    ports:
      - "4545:4545"
    restart: always
    networks:
      - default

  front:
    image: arcanjo-front
    depends_on:
      - back
    ports:
      - "80:80"
    restart: always
    networks:
      - default

networks:
  default: