version: '3.5'
services:
  postgresql:
    image: postgres
    ports:
      - "15432:15432"
    environment:
      POSTGRES_PASSWORD: 'db_pass'
      POSTGRES_USER: 'db_user'
      POSTGRES_DB: 'db_name'
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    command: -p 15432
    restart: always
    networks:
      - default

  back:
    image: arcanjo-back
    depends_on:
      - postgresql
    environment:
      - DB_PORT=15432
      - DB_HOST=postgresql
      - DIR_PREFIX=/storage/
      - CLI_DIR=/m08/
      - RESULTS_DIR=/results
      - LOGS_DIR=/m08/M08/log
      - THUMB_PREFIX=/caminho/para/pasta/
      - TZ=America/Sao_Paulo
      - VERSION_DATE=2.0 - 22/02/2022
    volumes:
      - "D:/:/storage"
      - "./results:/results"
      - "./logs:/m08/M08/log"
    ports:
      - "14545:4545"
    restart: always
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  front:
    image: arcanjo-front
    depends_on:
      - back
    ports:
      - "10000:80"
    restart: always
    networks:
      - default

networks:
  default: